### ISSUE TITLE
Ensure zero downtime upgrade

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#105]
## Description

When we introduce the eventing module, publishing events TO the EPP must be possible at all time.

**TODOs:**
- Eventing Manager should upgrade EPP successfully. ~~Currently, it cannot overwrite the owner references.~~
> ~~this can be solved with two deployments and a change of labels.~~

**Acceptance Criteria**

- [ ] dispatching of events can experience interruptions 
- [ ] publishing events to epp must be possible without interruptions

**How to test?**
- setup loadtester
- upgrade with running loadtester
- no events must be rejected from loadtester during upgrade (check logs of loadtest-publisher)

**Comment by mfaizanse** [comment]
https://github.com/kyma-project/eventing-manager/issues/71#issuecomment-1742585832
