### ISSUE TITLE
Move code from `eventing-controller` to `eventing-manager`

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/eventing-manager#106]
## Description
Instead of importing the eventing-controller, move the relevant code over to the eventing-manager repository. Adjust accordingly.

- Eventing-controller code remains in the Kyma repository
- No modification on the event-publisher-proxy is to be done within this ticket

Pair on this ticket, to enable fast reviews.

**For smoothest work**: any work on the eventing-manager repository will be stopped, once this ticket is in progress. People who are not working on this issue, shall be working on [the UI issue](https://github.com/kyma-project/eventing-manager/issues/120).

## Acceptance Criteria ✅
- [ ] Eventing manager should not have any dependencies on the `eventing-controller`
- [ ] The move is split up in many small PRs

**Comment by mfaizanse** [comment]
- https://kubebuilder.io/migration/multi-group.html

**Comment by mfaizanse** [comment]
- Renamed `api/operator.kyma-project.io` to `api/operator` and fixed imports.
- Renamed `internal/operator.kyma-project.io` to `internal/operator` and fixed imports.
- Copied `eventing-controller/api/v1alpha1` to `eventing-manager/api/eventing/v1alpha1`
- Copied `eventing-controller/api/v1alpha2` to `eventing-manager/api/eventing/v1alpha2`.
- Moved `internal/subscription` to `internal/eventing/subscription`.
- Removed `eventing-controller` from `go.mod`.
