### ISSUE TITLE
Proposal of Eventing Manager Architecture 

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-manager#12]
**Description**
Using the previous discussion as a basis, create a proposal for the eventing manager architecture.

**Acceptance Criteria**
- [ ] TAM Block Diagram for reconcilers (Eventing CR, Subscription CR) (optional create a sequence diagram to visualize how the various reconcilers interact)

**Comment by k15r** [comment]
The previous switching flow was based on watching for secrets:
![previous_layout](https://github.com/kyma-project/eventing-manager/assets/292906/9b241342-369b-4f44-a524-deee5e5d5083)

With the new module we will introduce a reconciler for the eventing cr. This will be the main/only driver for backend selection:
![eventing_reconciler](https://github.com/kyma-project/eventing-manager/assets/292906/461d471d-3085-4fd2-b914-acd572d4cfcc)
