### ISSUE TITLE
Provide correct cluster `domain` value to eventing-manager

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#137]
The `domain` env is set in eventing-manager deployment with dummy value ([here](https://github.com/kyma-project/eventing-manager/blob/7b9d669a376eea1555217e28b1230003a5da33ed/config/manager/manager.yaml#L80)). In kyma, this value was being overridden by kyma CLI, but now it is not. So we need to find a way to find the cluster domain and use the correct value in eventing-manager.

EventMesh subscriptions will not work if the domain value is incorrect.

There is a configMap in gardener cluster with this information, but we cannot reference it in ENV `valueFrom` because cross namespace reference is not allowed.
```
kubectl get cm -n kube-system shoot-info -o yaml
```

**idea:** have a field in the eventing CR; if this filed is empty, try to read the cm and get the domain name value. there is no cm, put the CR into error state.

This ticket should also fix this [bug](https://github.com/kyma-project/eventing-manager/issues/125#issuecomment-1759065459).

**Comment by grischperl** [comment]
Documentation missing
