### ISSUE TITLE
Validation and defaulting rules for the CR

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#17]
Description:

Implement CEL based validation and defaulting rules for the eventing-CR.

Hint: will be tested in the integration test

Acceptance:
- [x] define validation and defaulting rules for the CR and update the proposal
- [x] use CEL to validate eventing CR
- [x] use CEL to apply default values to the eventing CR

**Comment by grischperl** [comment]
https://github.com/muralov/eventing-manager/pull/1
