### ISSUE TITLE
Subscription is not ready after migration from kyma/eventing

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/eventing-manager#218]
On a cluster with Kyma/eventing and a `subscription` that is `ready=true`, removing `Kyma/eventing` and deploying `eventing-manager` will render the subscription to be `ready=false`. Deleting the `eventing-manager` will cause the `subscription` to be `ready=true` again.

- Questions:
   - What is the error message? Where in the code is it generated?
      - Error message was: `failed to find a NATS subscription for a subject: <nil>`
   - Could this be a NATS issue? Could an updated NATS-Server version fix this? We use [`2.9.18`](https://github.com/kyma-project/nats-manager/blob/6e97d31d1d6fab8fbe773494c8e2e669614377b3/resources/nats/values.yaml#L13) and the latest is [`2.10.4`](https://github.com/nats-io/nats-server/releases)

**Comment by mfaizanse** [comment]
We have a potential fix. We have tested it on 3 clusters and all good.
