### ISSUE TITLE
Create/Delete Publisher Proxy k8s resources with Eventing CR

### ISSUE THREAD

**Issue by muralov** [kyma-project/eventing-manager#24]
Currently, Publisher Proxy k8s resources (service, roles, etc.) are created with eventing-manager deployment. We should create/delete them only Eventing CR is created/deleted. Moreover, configmap containing event type prefix can be specified in Eventing CR with default value. 

**Acceptance Criteria**
 - [ ] create/delete EPP resources during eventing-CR reconciliation
   already implemented:
   - EPP deployment
   - hpa for EPP
  
   still required:
   - EPP services (metrics, publish, health)
   - service account
   - roles / bindings
   - ~peer authentication (only if istio is available, similar code is available in NATS-manager)~
      - Note: We decided to not manage `peer authentication` in eventing-manager. It will be created by the consumers of metrics.

   use go structs to specify/deploy these resources
   resources are owned by the eventing-manager
   changes should trigger reconciliation of eventing-cr

**Comment by mfaizanse** [comment]
We will not be creating `eventing-event-publisher-proxy` as it is not needed anymore!
