### ISSUE TITLE
move event type prefix from ConfigMap to Eventing-CR

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#25]
**Description**
in the eventing component the user is able to configure the event-type-prefix by modifying a configmap. With the new EventingCR a better location for this configuration is inside the EventingCR.

To ease future development of eventing-controller and eventing-manager as part of this story the currently reused parts from eventing-controller shall be duplicated into the eventing-manager codebase. Subscription managers will still be imported into the new eventing-manager.

**Acceptance**
- [x] expose `event-type-prefix` as a property in the Eventing CR
- [x] the default value is `sap.kyma.custom`
- [x] update busola in case it still requires this setting

**Comment by muralov** [comment]
according to the eventing [busola file](https://raw.githubusercontent.com/kyma-project/kyma/main/resources/eventing/charts/controller/templates/busola-extension.yaml), eventing ConfigMap is not used to extract the event type prefix.
