### ISSUE TITLE
Eventing Manager only uses generic labels for its runtime components

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#259]
## Description

only generic labels are used on runtime components deployed by eventing manager (or lifecycle manager for eventing-manager) to relate those component to the eventing manager.

## Acceptance
- [x] no generic labels are used on any of the eventing-manager components
- [x] labels can be used to distinguish clearly between components related to eventing-manager and other components
- [x] upgrading from previous versions of the eventing-manager works
- [x] labels are consistent
- [x] resources created by the eventing-manager are labeled with `app.kubernetes.io/created-by: eventing-manager` 
- [x] labels follow standards are documented [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) or [here](https://kubernetes.io/docs/reference/labels-annotations-taints/)

> if updating selectors is not supported at the moment (eg for deployments created for the EPP) just update the labels on the deployment, and in the pod template, but leave updating the actual selector to a followup ticket

**Comment by marcobebway** [comment]
For the time being, we added common labels for the resources managed by the Eventing manager.
Updating the selectors will happen in a later ticket which should focus on doing the update without downtime.
