### ISSUE TITLE
Allow empty backend-spec on eventing-cr

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#266]
## Description

when a user installs eventing it is installed with a default CR. This CR includes at this moment a configuration for NATS as a backend. With this configuration applied to any cluster it is mandatory to install the NATS module, or change the configuration to a valid backend configuration for EventMesh.

Out of the box without having NATS installed a fresh eventing installation will show up as erroneous. Supporting an empty backend configuration will fix this issue.

With the implementation of this issue we will support an empty backend configuration, that renders the eventing module into `warning` state. Eventing will NOT work with this configuration, but a warning will show that the user has to either configure the EventMesh backend, or install the NATS module and configure Eventing to use it.

## Acceptance
- [x] an empty (non existing) backend configuration is a valid configuration of the eventing-CR
  - no eventing related additional resources will be activated on the cluster (EPP, hpa for epp...)
- [x] the resource will be in `warning` state. A condition will provide information about the missing backend configuration
- [x] eventing will also be in `warning` state if
  - NATS is the active backend, but no NATS module is installed
  - eventMesh is the active backend, but the configured secret does not exist
- [x] any warning state for the Eventing CR will be reflected properly in busola (with human readable reason) 
- [x] the module will NOT support REMOVING existing eventing backend configuration 
  > hint: use validation rules `... self != oldself ...`
- [x] selecting the nats-backend option via Busola will display a notification that requires the user to activate the nats module.

## Work
- UI
- Backend
  - support empty backend-spec
  - cleanup for warning state
- CR validation (allow empty backend on create, not on update)
- Documentation
- Demo

**Comment by grischperl** [comment]
## To Do
- [ ] Update the documentation -> Mansur
- [ ] UI `ready` in overview should be green -> Carina
