### ISSUE TITLE
React to changes on ClusterRole and ClusterRoleBindings

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#33]
The watcher for ClusterRoles and ClusterRoleBindings are not working as done for other k8s resources. For example: deleting the clusterRole/ClusterRoleBinding is not triggering reconciliation.

**Hint:** Maybe watching cluster-scoped resources needs a different way.

**AC:**
- [x] Any changes on deployed ClusterRoles and ClusterRoleBindings should trigger reconciliation.
- [x] Uncomment disabled tests for ClusterRoles and ClusterRoleBindings ([here](https://github.com/kyma-project/eventing-manager/blob/fd0968b69c2bc4bbdf0bc01fcf39ccb7176d2dc8/internal/controller/eventing/integrationtests/controller/integration_test.go#L415)).

**Comment by muralov** [comment]
It works in a real cluster but not a local envtests.

**Comment by muralov** [comment]
it seems it is not working for newer K8s version
