### ISSUE TITLE
enhance documentation for states of eventing-CR

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#346]
The state of the eventing CR is partially depending on the state of the nats-module/nats-cluster
Create a documentation that explains in a human readable form which state of the backend / configuration of the eventing-module leads to which state on the eventing-CR.

eg. 

| overall state | eventing-cr-configuration | backend-situation |
|--------------|---------------------------|-------------------|
| warn | all ok | no backend available |

**Comment by muralov** [comment]
blocked until the [issue](https://github.com/kyma-project/eventing-manager/issues/267) is completed.
