### ISSUE TITLE
Build binaries / Trigger build job for signed image

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-manager#363]
## Description
- Build job for signed release image
- Image not tagged immediately
- Image tagged after changelog, draft release, and manifest upload is completed
- E2E and Upgrade test (#364) run on the image

## Acceptance
- [ ] Do not tag image yet
- [ ] Run e2e test on image
- [ ] Run upgrade test on image

## Reguirement
- [x] #370

**Comment by friedrichwilken** [comment]
We might not need this since we do only create draft releases for now.
