### ISSUE TITLE
Enable EventMesh Backend

### ISSUE THREAD

**Issue by muralov** [kyma-project/eventing-manager#37]
Enable EventMesh backend for Eventing Manager. We'll have one controller in Eventing Manager.
Backend switching is excluded as it'll be implemented in separate issues. The prerequisite is implementation of subscription in nats mode https://github.com/kyma-project/eventing-manager/issues/8

Steps:
- Create EPP for EventMesh Mode (logic is copied into eventing-manager, probably needs to be improved)
- Start Subscriber for EventMesh Mode (EC package is imported and called)

**Acceptance Criteria**
- [ ] Eventing Manager should work in EventMesh mode

**Comment by mfaizanse** [comment]
Please demo it!
