### ISSUE TITLE
Remove Subscription v1alpha1 version

### ISSUE THREAD

**Issue by muralov** [kyma-project/eventing-manager#442]
**Description**
Delete the v1alpha1 version of Subscription API

**Acceptance Criteria**
- [x] Delete v1alpha1  Subscription CRD
- [x] Delete v1alpha1 code
- [x] Delete v1alpha1 webhooks
- [x] Verify that the upgrade to this version has no issue
- [x] Delete v1alpha1 E2E tests
- [ ] ~~Check if any other components not using v1alpha1 related packages, for example EPP is using it [here](https://github.com/kyma-project/eventing-publisher-proxy/blob/main/pkg/handler/handler.go)~~ We decided to keep it as it is.
- [x] Verify the load tester that is not using v1alpha1
- [x] Delete internal and external documentations of v1alpha1

**Comment by mfaizanse** [comment]
Checklist for `Delete internal and external documentations of v1alpha1`:
- [ ] On-call guides
- [ ] websites
- [ ] SAP help 
- [ ] docs

**Comment by mfaizanse** [comment]
Checklist for `Verify the load tester that is not using v1alpha1`:

- For `v1alpha1` we have a [legacy branch](https://github.com/kyma-project/eventing-tools/tree/loadtest-subscription-v1alpha1).
