### ISSUE TITLE
react to changes of the istio module

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#450]
## Description

On a cluster eventing was installed before istio was installed. This lead to alerts on SRE side as epp could not be scraped anymore.

## Acceptance
- [ ] istio related resources should be created by eventing-manager when istio becomes available. Removing those resources is not necessary on istio removal, as istio removes them as well.

**Comment by gczuczy** [comment]
One of the two pods did not have a sidecar:
```
eventing-publisher-proxy-78d9695498-c9pts                     2/2     Running     0             13h
eventing-publisher-proxy-78d9695498-p8jkb                     1/1     Running     0             13h
```
Interestingly, the scraping worked for the one without a sidecar.

We needed to bounce the eventing proxy manager, so it creates the required peerauthentication resources that complete the service mash configuration, and by that scraping started to work again.

**Comment by marcobebway** [comment]
Blocked until we figure out what should we do about the eventing-manager pod itself, as it will require a restart as well to get the istio sidecar which is needed to dispatch events to subscribers in case of the NATS backend.
