### ISSUE TITLE
Pause/unpause functionality for NATS Dispatcher

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/eventing-manager#518]
**Description**

We want to be able to pause and unpause the Subscription in the case of an invalid sink to avoid the retries to the unreachable sink.

**Pause/un-pause scenarios:**

1. Automatic pause by the reconciler
- In that case the reconciler renders a subscription not ready automatically in case the sink is not valid
- un-pause, as soon as the sink passes the validity check
 - It must NOT put a pause label on the subscription, as this would force the user to interfere with the subscription before it is resumed
 -  requeue the paused subscription
 
2. Manual pause
- In that case any user of eventing can add a  “pause” label to the Subscription
- Un-pause, once the label is gone

**Implementation Tasks**

This Feature should **only** be implemented for **v1alpha2** Subscription version.

- [ ]  in the paused state Subscription should be not-ready
- [ ]  delete the NATS-server Subscription and leave the consumer (hence, the interest)
- [ ]  add a paused sub condition to the Kyma Subscription status

_Note: check if closing the Subscription on the NATS side would help_

**Acceptance Criteria**

- [ ] Pause/unpause functionality is implemented
- [ ] A test case is written which proves that a NATS Subscription can be paused and resumed without losing any events.

**Follow-ups**

https://github.com/kyma-project/kyma/issues/16329

**Comment by k15r** [comment]
We do not plan to implement this
