### ISSUE TITLE
Eventing-CR condition `BackendAvailable` does not change from `BackendNotAvailable`

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#533]
## Description

1. install the eventing-module
2. it will be in `warning` state as no backend was configured
3. configure a backend

## Expected

* eventing becomes ready and all conditions are in a 'green' state

## Actual

* eventing becomes ready
* the `backendAvailable` condition is still not green. Reason: `backend not available`

**Comment by marcobebway** [comment]
Should be fixed as part of https://github.com/kyma-project/eventing-manager/issues/506.
