### ISSUE TITLE
Review and Update Eventing-related content in Kyma Learning Journey

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/eventing-manager#548]
**Description**

[Delivering Side-by-Side Extensibility based on SAP BTP, Kyma runtime](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime) Kyma Learning Journey got outdated. Markus Haug would like to cooperate with us in updating it.

For the Eventing module, we need to take care of the following items:

- [x] [Discovering Kyma Eventing](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/discovering-kyma-eventing_b0642608-bbf3-494a-a5a3-aef99e414e28)
- [ ] [Creating a subscription using Kyma Eventing](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/creating-a-subscription-using-kyma-eventing_d6cbbbc8-06c1-439e-978c-2adeb90278e0)

**Reasons**

Content update requiring cross-team collaboration.

**Assignees**

@kyma-project/technical-writers
@k15r 

**Attachments**

See #5292 in internal /backlog

**Comment by mfaizanse** [comment]
The PR to update the content is merged to `KYM400_Content` repository. The [page](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/creating-a-subscription-using-kyma-eventing_d6cbbbc8-06c1-439e-978c-2adeb90278e0) will be updated later by Markus team.
