### ISSUE TITLE
About aarch64

### ISSUE THREAD

**Issue by rzsap** [kyma-project/eventing-manager#551]
Hello,

I met below error when start eventing-manager on aarch64 Ubuntu using k3s:
` exec /manager: exec format error`

I cannot find the platform information from the image manifest:
https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/eventing-manager/sha256:1444925522066fdbfce8ca80aee7974e653f70c5551e8a803c55f9e636567ba1;tab=manifest
 
So just want to check whether aarch64 is supported or not? 

Thanks
Reggie

**Comment by rzsap** [comment]
Tried `docker manifest inspect -v europe-docker.pkg.dev/kyma-project/prod/eventing-manager:1.1.0` again.
From the output, seems only amd64 supported.
`{
		"mediaType": "application/vnd.oci.image.manifest.v1+json",
		"digest": "sha256:1444925522066fdbfce8ca80aee7974e653f70c5551e8a803c55f9e636567ba1",
		"size": 1810,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}`

**Comment by mfaizanse** [comment]
We only support `amd64`.
