### ISSUE TITLE
Update Condition for Subscription Controller in Eventing Status for NATS

### ISSUE THREAD

**Issue by muralov** [kyma-project/eventing-manager#65]
There is a condition reflecting whether [Subscription controller](https://github.com/kyma-project/eventing-manager/blob/01f5bd766879a4db7e233f4a06876e152ac189fb/api/v1alpha1/eventing_types.go#L38) for NATS/EventMesh is ready or not. 

It is already done for EventMesh [here](https://github.com/muralov/eventing-manager/blob/d564e4be30f0fb58e88c72c00b8ed8e2b974e3bd/internal/controller/eventing/controller.go#L304).

**Acceptance Criteria**:
- [ ] Replicate the change for NATS backend as well

**Comment by k15r** [comment]
We do not plan to implement this
