### ISSUE TITLE
Improve EventMesh Secret format Validation to Use DNS Regex

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-manager#67]
### Description
- `EventMeshSecret` validation rule [here](https://github.com/kyma-project/eventing-manager/blob/6b9579d600874b8f6d1e711bd2374bb90b2768b7/api/v1alpha1/eventing_types.go#L142C1-L142C1)
- Currently: very simplex Regex for validation
- Better: DNS provides a Regex for secret validation

### Task
- [ ] Update `EventMeshSecret` validation rule to use the Regex pattern provided by DNS (in kubernetes pkg).

**Comment by k15r** [comment]
We do not plan to implement this
