### ISSUE TITLE
Block eventing-CR removal if resources owned by it exist in the cluster

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#79]
## Description

 Same as with nats-manager. you cannot remove the module as long as subscriptions are configured in the cluster, regardless of them being NATS or EventMesh subscriptions. Once everything is cleaned up, the module can go.

## Tasks
- block deletion of the eventing-cr until all resources created by it are removed from the cluster
  - subscriptions
  - APIRules
- DO NOT cleanup subscriptions. This task is for the user. As soon as they remove all subscriptions the eventing-CR is ready to be deleted (finalizer removed from it)

**Comment by muralov** [comment]
Checking only existence of subscription CR is enough as API Rules have it as owner reference.
