### ISSUE TITLE
Enable Subscription Manager in NATS Mode

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/eventing-manager#8]
**Description**

The current implementation of a reconciler for Eventing-CRs checks that all infrastructure for Eventing in NATS mode is set up correctly. With this ticket we need to enable reconciling Subscriptions in NATS mode. As this logic already exists in the current implementation in eventing-controller, the way to migrate the existing logic into the new reconciler is by importing the package of the eventing-controller and reuse it.

**Note**
The existing logic is imported as a package to avoid code duplication so long as there is still work to be done on the eventing-controller. This ticket is only about starting subscription manager.

**Acceptance Criteria:**
- [x] reconcile kyma subscription and create nats-infrastructure (stream, consumers, dispatcher)
- [x] existing unit and integration tests should continue to pass as before
- [x] apply the configuration from the eventing CR as defined in the proposal

**Comment by mfaizanse** [comment]
- [ ] Check deletion of CR and recreation.
- [ ] Make target to copy subscription and application CRs.
- [ ] Test on a vanilla cluster again.
