### ISSUE TITLE
Proposal: How to migrate nats and eventmesh reconciler into eventing manager

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/eventing-manager#9]
**Description**
- When the eventing CR reconciliation gets triggered, how should the NATS or EventMesh infrastructure be provisioned?
- When the user changes the backend, how will the old backend stop and how would the new get started?
- Should we migrate the subscription managers from eventing controller?
- Should we convert from the current codebase (same codebase in modular fashion).
- What about time concerns? How to do so?

**Acceptance Criteria**
- [ ] Find out if we already documented the needed changes to a modular codebase
- [ ] Have a flow chart how migration should look like

**Comment by k15r** [comment]
Not needed anymore
